### ISSUE TITLE
Неудобно удалять текст

### ISSUE THREAD

**Issue by AnroMel** [AleksandrTabanakov/Online_Translator_Issues#1]
1. Запускаю приложение
2. Вставляю код
3. Просматриваю код на другом языке
4. Чтобы удалить нужно самому все стирать
Ожидаемо: Есть кнопка для стирания написанного кода

**Comment by AleksandrTabanakov** [comment]
Кнопка была добавлена. Спасибо, что помогаете нам :+1:
