### ISSUE TITLE
Странный функционал кнопки

### ISSUE THREAD

**Issue by vallerili** [AleksandrTabanakov/Online_Translator_Issues#2]
1. Запускаю приложение
2. На вкладке FAQ встречает приветственный текст
3. Ниже текста есть кнопка копировать
![image](https://user-images.githubusercontent.com/113391020/205716448-bb82a8ef-63d1-4628-a1bf-ebf7e75e698b.png)

4. Зачем копировать приветственный текст
5. Ожидалось: Будет кнопка "Понятно", которая перебрасывает на главную страницу

**Comment by AleksandrTabanakov** [comment]
Спасибо, исправили)
