### ISSUE TITLE
Неудобный scroll кода

### ISSUE THREAD

**Issue by IrinaOsotova** [AleksandrTabanakov/Online_Translator_Issues#3]
1. Запускаю приложение
2. Вставляю код
3. Перевожу на другой язык программирования
4. Программа длинная. Неудобно листать текст. Приходится нажимать на это поле и вести курсор вверх.
![image](https://user-images.githubusercontent.com/113375568/205719509-5b580954-8366-4d65-bca8-f60cfa179204.png)
![image](https://user-images.githubusercontent.com/113375568/205719564-66004bca-b93d-435e-b354-32eea55a8956.png)
Ожидаемо: удобный scroll кода

**Comment by AleksandrTabanakov** [comment]
спасибо за то что проявляете интерес к нашему продукту! Обязательно посоветуемся с коллегами и сделаем оптимальный вариант
