### ISSUE TITLE
Вылетает приложение

### ISSUE THREAD

**Issue by 943ml1n** [AleksandrTabanakov/Online_Translator_Issues#4]
1. Открываю приложение
2. В поле ввёл следующий текст: "яблоко банан"
3.  Приложение вылетело
![image](https://user-images.githubusercontent.com/116759793/205733831-13e8dc8c-e0c2-4adf-8d11-88d0c33035b4.png)
Ожидалось: Уведомление о некорректном вводе.

**Comment by AleksandrTabanakov** [comment]
Исправили!. Спасибо, что помогаете нам
