### ISSUE TITLE
Приложение выводит лишний ошибочный текст

### ISSUE THREAD

**Issue by sealwestrow** [AleksandrTabanakov/Online_Translator_Issues#5]
1. Открываю приложение
2. Вставляю код программы на языке Pascal
3. В конце дописываю следующие слова: "ьутктет, 134тутькьк, 1456лю"

![image](https://user-images.githubusercontent.com/99202907/205734874-3eef2c14-1570-4023-8735-0a7707a5a0de.png)

4. Нажимаю "Перевести"
5. Выводится код на языке C#, в котором присутствуют слова: "ьутктет, 134тутькьк, 1456лю"

![image](https://user-images.githubusercontent.com/99202907/205735138-d6bb1ec6-b800-4b4c-91cb-9c5e9b246faa.png)

Ожидалось: переведенный код не будет содержать слов: "ьутктет, 134тутькьк, 1456лю", или появится предупреждение о некорректном вводе

**Comment by AleksandrTabanakov** [comment]
Спасибо за ваше неравнодушие 👍 в данном случае это не является багом. Т.к. программа не может пока что учесть все возможные переводы, поэтому было принято решение не удалять подобные случае, а оставлять в коде, для того, чтобы пользователь смог увидеть, что в этом месте перевод не осуществился
